version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    env_file:
      - local.env
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 80:8000